spring:
  datasource:
    url: jdbc:mysql://local:3306/soonmaptest
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

# Naver Config Vars
  client:
    id: ${Client ID}
    secret: ${Client Secret}
    redirect-uri: ${CALLBACK URL}
    session-state: ${SESSION_STATE}
  profile-api-url: ${PROFILE_API}

# Kakao Config Vars
  kakao:
    client_id: ${KAKAO_RESTAPI_KEY}
    redirect_uri: ${KAKAO_REDIRECT_URL}
    profile-api-url: https://kapi.kakao.com/v2/user/me
    client_secret: ${KAKAO_CLIENT_SECRET}

# S3
cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_REFRESH_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

CLOUD_FRONT_URL: ${CLOUD_FRONT_URL}
JWT_SECRET_KEY: ${JWT_SECRET_KEY}
REDIS_ENDPOINT: ${REDIS_ENDPOINT}