name: develop

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: actions/checkout@v3
      - name: Make application.properties
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.PROPERTIES_TEST }}" > src/main/resources/application-test.yml
          find src

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PW }}
          docker build --build-arg PROFILE=test -t ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_DEV_IMAGE_NAME }} .
          docker push ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_DEV_IMAGE_NAME }}

      - name: EC2 Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_DEV_IMAGE_NAME }}
            docker stop ${{ secrets.DOCKER_DEV_IMAGE_NAME }}
            docker run -d --rm --name ${{ secrets.DOCKER_DEV_IMAGE_NAME }} --network sm-net -p 8080:8080 ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_DEV_IMAGE_NAME }}
            docker rmi $(docker images -f "dangling=true" -q)
            docker images -a
            docker ps -a